### ISSUE TITLE
Slow

### ISSUE THREAD

**Issue by tj** [creationix/pattern#1]
It's neat in respect to prototypal inheritance, but slow ATM (crappy benchmark, but illustrates):

```
Running 500000 times:
  - Pattern:
    4445ms
  - Constructor:
    24ms
```

http://gist.github.com/547641

**Comment by tj** [comment]
seems quite a lot faster without Object.seal()

**Comment by creationix** [comment]
I removed seal and re-implemented with an internal "new" it's quite snappy now.
